export { About } from "./About";
export { Banner } from "./Banner";
export { CartModal } from "./CartModal";
export { Category, Categories } from "./Categories";
export { Footer } from "./Footer";
export { Header, Hero, Navbar } from "./Header";
export { Main, Featured } from "./Main";
export { Product, InTheBoxItem } from "./Product";
export { Total } from "./Total";
export { ConfirmationModal } from "./ConfirmationModal";
export { Fieldset } from "./Fieldset";
